name = "Minecraft Server Pack"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "804346114c477aa393c888333e2a3f292192d26b8be458dfc26bb8035c4d39ff"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
