name = "Minecraft Server Pack"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e624679827114bac72d08858e17e9274a2dc6bacd0230e5ec0689ae413254df7"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
